### ISSUE TITLE
Uncaught Invariant Violation error in console

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#669]
The console shows an error that doesn't seem to have consequences on the site:

```
Uncaught Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at e.exports (https://developers.italia.it/dist/bundle.js:320:94349)
    at Object._renderNewRootComponent (https://developers.italia.it/dist/bundle.js:390:175485)
    at Object._renderSubtreeIntoContainer (https://developers.italia.it/dist/bundle.js:390:176560)
    at Object.render (https://developers.italia.it/dist/bundle.js:390:176687)
    at C (https://developers.italia.it/dist/bundle.js:370:12059)
    at f (https://developers.italia.it/dist/bundle.js:410:152954)
    at Er (https://developers.italia.it/dist/bundle.js:410:153387)
    at Module.<anonymous> (https://developers.italia.it/dist/bundle.js:460:156367)
    at n (https://developers.italia.it/dist/bundle.js:1:110)
    at https://developers.italia.it/dist/bundle.js:1:902
```

**Comment by bfabio** [comment]
The proper fix would be to use [swagger-ui-react](https://github.com/swagger-api/swagger-ui/issues/3955#issuecomment-468953136), which addresses this very problem.

Problem is `swagger-ui-react` [doesn't support custom plugins](https://github.com/swagger-api/swagger-ui/issues/5367) and that's the whole point of our Swagger integration.

Pushing the issue back for now since the issue doesn't seem to have any practical effect on the user experience.

Related to #695

**Comment by emilioSp** [comment]
@bfabio I've found the cause of the problem, but unfortunately at the moment, I don't have a solution.

The warning is due to the fact that [here](https://github.com/italia/developers.italia.it/blob/master/assets/js/swagger-custom.js#L55) the element `#swagger` is not present in the dom.
